[dependencies]
vaas = { version = "6.0.0" }
tokio = { version = "1.37", features = ["rt-multi-thread", "macros"] }
clap = { version = "4.5.4", features = ["env", "cargo"] }
reqwest = "0.12.4"
futures = "0.3.30"
dotenv = "0.15"
urlencoding = "2.1.2"  # Add this line for URL encoding support

